[build]
target = "x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "link-arg=-Wl,--gc-sections",
    "-C", "link-arg=-Wl,--strip-all",
    "-C", "link-arg=-Wl,-z,relro",
    "-C", "link-arg=-Wl,-z,now",
    "-C", "link-arg=-fstack-protector-strong",
]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
rustflags = [
    "-C", "link-arg=-Wl,--gc-sections",
    "-C", "link-arg=-Wl,--strip-all",
    "-C", "link-arg=-Wl,-z,relro",
    "-C", "link-arg=-Wl,-z,now",
    "-C", "link-arg=-fstack-protector-strong",
]

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
rustflags = [
    "-C", "link-arg=-Wl,--gc-sections",
    "-C", "link-arg=-Wl,--strip-all",
    "-C", "link-arg=-Wl,-z,relro",
    "-C", "link-arg=-Wl,-z,now",
    "-C", "link-arg=-fstack-protector-strong",
]

[target.thumbv7em-none-eabi]
linker = "arm-none-eabi-gcc"
rustflags = [
    "-C", "link-arg=-Wl,--gc-sections",
    "-C", "link-arg=-Wl,--strip-all",
    "-C", "link-arg=-nostartfiles",
    "-C", "link-arg=-Tlink.x",
]

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
opt-level = 0
debug = true

[profile.bench]
opt-level = 3
lto = "thin"
codegen-units = 1 